title: "Jahnavi Ravi Portfolio"
email: "jahnaviravi1998@gmail.com"
description: "A portfolio site for showcasing my projects in 3D Computer Vision."
theme: minima
baseurl: "" # Leave blank unless the site is in a subdirectory
url: ""     # Add your site's domain here if hosted online (e.g., "https://example.com")
permalink: pretty

# Markdown settings
markdown: kramdown
highlighter: rouge

# Include folders and files
include:
  - _pages
  - _posts
  - assets

# Social media links (optional, for footer or sidebar links)
social_links:
  linkedin: "https://linkedin.com/in/jahnaviravi"
  github: "https://github.com/Jahnavi-Rav"


# Author metadata
author:
  name: "Jahnavi Ravi"
  email: "jahnaviravi1998@gmail.com"
